# Generated by Django 2.0.1 on 2018-02-01 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviewer.Data')),
            ],
        ),
    ]
